# Config file for automatic testing at travis-ci.org

sudo: false
language: python
env:
  - MOZ_HEADLESS=1
addons:
  firefox: "56.0"

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=chrome
    - python: 3.6
      env: TOX_ENV=firefox
    - python: 3.6
      env: TOX_ENV=flake8

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xvzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - chmod +x $PWD/geckodriver/geckodriver
  - export PATH=$PATH:$PWD/geckodriver

  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver

install:
  - pip install tox coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

after_success:
  - coveralls
